language: c
sudo: false
git:
  submodules: false
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
env:
  - R_LIBS_USER=~/.R/library
cache:
  directories:
    $R_LIBS_USER
before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (!require("devtools")) install.packages("devtools", repos = "http://cran.rstudio.com/")'
  - Rscript -e 'if (!require("roxygen2")) devtools::install_github("klutometis/roxygen@v5.0.1")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'
script:
  - Rscript -e 'library(checkr); res <- try(devtools::check()); quit(save = "no", status = if (isTRUE(res)) { 0 } else { 1 }, runLast = FALSE)'
after_success:
  - Rscript -e 'library(covr);coveralls()'
